steps:
# Get kubernetes cluster config and save to /kube
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['config', 'current-context']
  volumes:
  - name: 'kube'
    path: '/kube'
  env:
  - 'KUBECONFIG=/kube/config'
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=demo'
  - 'CLOUDSDK_CONTAINER_USE_APPLICATION_DEFAULT_CREDENTIALS=true'
# Get GRepo
- name: 'gcr.io/cloud-builders/git'
  args: [ 'clone', 'https://github.com/chili-oregano/gcp-policy-management.git' ]
- name: 'ubuntu'
  args: [ '/workspace/.bin/config-validator', 'vet', '--path=/workspace' ]
  volumes:
  - name: 'kube'
    path: '/kube'
  env:
  - 'KUBECONFIG=/kube/config'
