apiVersion: bespin.dev/v1
kind: IAMPolicy
metadata:
  creationTimestamp: null
  name: project-checkout-srvc-iam
spec:
  bindings:
  - members:
    - user:dev-bob@chili-oregano.com
    role: roles/owner
  resourceRef: {}
status: {}
