apiVersion: bespin.dev/v1
kind: IAMPolicy
metadata:
  creationTimestamp: null
  name: project-ferrous-purpose-235601-iam
spec:
  bindings:
  - members:
    - user:zhuzenglu@google.com
    - user:vendor-sam@clearify.co
    role: roles/editor
  resourceRef: {}
status: {}
